# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Supress warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import json
from pprint import pprint
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [3]:
# read the csv file from weatherpy exercice and convert it to data frame

cities = pd.read_csv("../WeatherPy/output_data/cities_weather.csv")
cities.tail()

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
564,armizonskoye,-19.2500,146.8000,68.88,32.0,0.0,6.91,AU,1.658972e+09
565,abu kamal,7.3167,13.5833,62.83,97.0,100.0,0.60,CM,1.658972e+09
566,yerbogachen,-20.3167,118.5667,75.25,31.0,0.0,11.50,AU,1.658972e+09
567,yamoussoukro,-11.3847,43.2844,75.54,70.0,37.0,5.73,KM,1.658972e+09
568,ukholovo,-6.5742,-76.1367,77.85,86.0,47.0,0.94,PE,1.658972e+09

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:

gmaps.configure(api_key=g_key)

In [5]:
# create humudity map
locations = cities[['Lat', 'Lng']]
weight = cities["Humidity"]

In [6]:
# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights= weight, 
                                 dissipating=False, max_intensity=10,
                                 point_radius=1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [7]:
# Narrow down the DataFrame to find your ideal weather condition. For example:
# A max temperature lower than 80 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.

# Drop any rows that don't satisfy all three conditions. You want to be sure the weather is ideal.


ideal_vacaton_cities = cities.loc[(cities['Max Temp'] > 70) & (cities['Max Temp'] < 80) & (cities["Wind Speed"] < 10) &(cities["Cloudiness"]==0)].dropna()
ideal_vacaton_cities

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
4,gavle,4.9333,-52.3333,76.08,1.0,0.0,0.00,GF,1.658971e+09
9,oranjestad,32.6667,-17.1000,72.23,74.0,0.0,5.08,PT,1.658972e+09
92,los llanos de aridane,31.6100,34.7642,77.40,68.0,0.0,2.98,IL,1.658972e+09
103,athabasca,37.5228,42.4594,70.56,16.0,0.0,6.98,TR,1.658972e+09
151,mundo nuevo,31.6682,20.2521,78.75,68.0,0.0,4.45,LY,1.658972e+09
162,saint george,-19.5314,-54.0439,72.95,32.0,0.0,2.95,BR,1.658972e+09
209,rio grande,53.2168,-114.9854,74.68,75.0,0.0,7.38,CA,1.658972e+09
222,antalaha,41.1415,-73.3579,77.43,64.0,0.0,5.99,US,1.658972e+09
230,poum,35.0367,32.4264,75.02,45.0,0.0,1.30,CY,1.658972e+09
259,saldanha,41.3712,-73.4140,76.77,72.0,0.0,0.00,US,1.658972e+09
278,goba,40.4394,113.1536,71.19,53.0,0.0,2.44,CN,1.658972e+09
307,yar-sale,38.0000,-3.5000,73.02,46.0,0.0,1.05,ES,1.658972e+09
331,san vicente,39.4625,-3.6080,73.15,36.0,0.0,5.28,ES,1.658972e+09
345,keshan,41.2835,-70.0995,75.25,85.0,0.0,6.91,US,1.658972e+09
364,jiuquan,37.8486,40.6658,74.93,25.0,0.0,2.10,TR,1.658972e+09
373,olafsvik,39.0500,-27.9833,71.22,81.0,0.0,7.74,PT,1.658972e+09
389,bargal,31.3525,27.2453,75.40,83.0,0.0,2.30,EG,1.658972e+09
444,sweetwater,-9.8756,-56.0861,71.71,41.0,0.0,2.51,BR,1.658972e+09
481,santiago del estero,31.6315,-8.0083,75.27,53.0,0.0,5.75,MA,1.658972e+09
491,saint-paul-les-dax,38.2414,16.2623,79.32,66.0,0.0,6.44,IT,1.658972e+09
499,finschhafen,-12.9025,45.0761,73.38,66.0,0.0,9.89,YT,1.658972e+09
501,shache,55.3422,-131.6461,77.47,41.0,0.0,9.22,US,1.658972e+09
515,ilo,36.8886,4.1198,76.73,69.0,0.0,8.12,DZ,1.658972e+09
528,gao,32.5341,20.5791,77.94,82.0,0.0,4.68,LY,1.658972e+09
540,impfondo,43.2128,-75.4557,72.73,83.0,0.0,1.99,US,1.658972e+09

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [8]:
hotels_nearby = ideal_vacaton_cities[["City", "Country", "Lat", "Lng"]]
hotels_nearby["Hotel Name"] = ""
hotels_nearby

                      City Country      Lat       Lng Hotel Name
4                    gavle      GF   4.9333  -52.3333
9               oranjestad      PT  32.6667  -17.1000
92   los llanos de aridane      IL  31.6100   34.7642
103              athabasca      TR  37.5228   42.4594
151            mundo nuevo      LY  31.6682   20.2521
162           saint george      BR -19.5314  -54.0439
209             rio grande      CA  53.2168 -114.9854
222               antalaha      US  41.1415  -73.3579
230                   poum      CY  35.0367   32.4264
259               saldanha      US  41.3712  -73.4140
278                   goba      CN  40.4394  113.1536
307               yar-sale      ES  38.0000   -3.5000
331            san vicente      ES  39.4625   -3.6080
345                 keshan      US  41.2835  -70.0995
364                jiuquan      TR  37.8486   40.6658
373               olafsvik      PT  39.0500  -27.9833
389                 bargal      EG  31.3525   27.2453
444             sweetwater      BR  -9.8756  -56.0861
481    santiago del estero      MA  31.6315   -8.0083
491     saint-paul-les-dax      IT  38.2414   16.2623
499            finschhafen      YT -12.9025   45.0761
501                 shache      US  55.3422 -131.6461
515                    ilo      DZ  36.8886    4.1198
528                    gao      LY  32.5341   20.5791
540               impfondo      US  43.2128  -75.4557

In [9]:
# set the parameters



parameter = { 
            "radius": 50000,
            "types": "hotels",
            "key": g_key}
     
              
          
      

# use ierrows to loop through dataframe

for index, row in hotels_nearby.iterrows():
    
    # get the latitude and longtitude from the current row
    lat = row["Lat"]
    lng = row["Lng"]
    
    # append the obtained latitude and longtitude to params dict
    parameter["location"] = f"{lat},{lng}"
  
    
    # utilize google places api to find the hotels
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    
    hotel_name= requests.get(url,parameter).json()
 
   # pprint(hotel_address) #['results'][0]['name']
    
    # Apply exception rule incase and result wasn't found
    try:
        # generate hotel names to the dataframe
        hotels_nearby.loc[index,"Hotel Name"] = hotel_name['results'][0]['name']
    except:
        print(" No hotel was found in {row['City']}. skip")
        
hotels_nearby

                      City Country      Lat       Lng      Hotel Name
4                    gavle      GF   4.9333  -52.3333         Cayenne
9               oranjestad      PT  32.6667  -17.1000   Ribeira Brava
92   los llanos de aridane      IL  31.6100   34.7642      Kiryat Gat
103              athabasca      TR  37.5228   42.4594          Şırnak
151            mundo nuevo      LY  31.6682   20.2521           Suluq
162           saint george      BR -19.5314  -54.0439         Camapuã
209             rio grande      CA  53.2168 -114.9854  Drayton Valley
222               antalaha      US  41.1415  -73.3579         Norwalk
230                   poum      CY  35.0367   32.4264           Peyia
259               saldanha      US  41.3712  -73.4140         Danbury
278                   goba      CN  40.4394  113.1536          Datong
307               yar-sale      ES  38.0000   -3.5000           Baeza
331            san vicente      ES  39.4625   -3.6080      Madridejos
345                 keshan      US  41.2835  -70.0995       Nantucket
364                jiuquan      TR  37.8486   40.6658          Bismil
373               olafsvik      PT  39.0500  -27.9833           Velas
389                 bargal      EG  31.3525   27.2453    Marsa Matruh
444             sweetwater      BR  -9.8756  -56.0861   Alta Floresta
481    santiago del estero      MA  31.6315   -8.0083       Marrakesh
491     saint-paul-les-dax      IT  38.2414   16.2623         Siderno
499            finschhafen      YT -12.9025   45.0761       Mamoudzou
501                 shache      US  55.3422 -131.6461       Ketchikan
515                    ilo      DZ  36.8886    4.1198      Tizi Ouzou
528                    gao      LY  32.5341   20.5791         Al Marj
540               impfondo      US  43.2128  -75.4557            Rome

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotels_nearby.iterrows()]
locations = hotels_nearby[["Lat", "Lng"]]

In [11]:
# Add marker layer ontop of heat map
marker = gmaps.marker_layer(locations, info_box_content =hotel_info )
fig.add_layer(marker)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))